language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

sudo: false

install:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then rustup component add rustfmt; fi

script:
  - if [[ $TRAVIS_RUST_VERSION == "stable" && $TRAVIS_OS_NAME == "linux" ]]; then cargo fmt -- --check; fi
  - cargo build --verbose
  - cargo test --verbose

notifications:
  email:
    on_success: never
